### ISSUE TITLE
NameError: uninitialized constant DynamicSitemaps::SitemapGenerator::ActiveRecord

### ISSUE THREAD

**Issue by stabenfeldt** [lassebunk/dynamic_sitemaps#25]
I'm using  dynamic_sitemaps (2.0.0) and Rails-4.1.1

**config/sitemap.rb**

```
require 'dynamic_sitemaps'
host 'www.test.com'

sitemap :site do
  url root_url, last_mod: Time.now, change_freq: "daily", priority: 1.0
end
```

``` ruby
✗  rake sitemap:generate
Digest::Digest is deprecated; use Digest
Generating sitemap...
rake aborted!
NameError: uninitialized constant DynamicSitemaps::SitemapGenerator::ActiveRecord
/gems/dynamic_sitemaps-2.0.0/lib/dynamic_sitemaps/sitemap_generator.rb:143:in `format_url'
/gems/dynamic_sitemaps-2.0.0/lib/dynamic_sitemaps/sitemap_generator.rb:39:in `write_url'
/gems/dynamic_sitemaps-2.0.0/lib/dynamic_sitemaps/sitemap_generator.rb:138:in `url'
/Users/martins/Work/API/Trenger/config/sitemap.rb:6:in `block in generate'
//gems/dynamic_sitemaps-2.0.0/lib/dynamic_sitemaps/sitemap_generator.rb:33:in `instance_eval'
//gems/dynamic_sitemaps-2.0.0/lib/dynamic_sitemaps/sitemap_generator.rb:33:in `write_urls'
//gems/dynamic_sitemaps-2.0.0/lib/dynamic_sitemaps/sitemap_generator.rb:16:in `generate'
//gems/dynamic_sitemaps-2.0.0/lib/dynamic_sitemaps/generator.rb:57:in `sitemap'
/Users/martins/Work/API/Trenger/config/sitemap.rb:5:in `generate'
/gems/dynamic_sitemaps-2.0.0/lib/dynamic_sitemaps/generator.rb:10:in `instance_eval'
/gems/dynamic_sitemaps-2.0.0/lib/dynamic_sitemaps/generator.rb:10:in `generate'
/gems/dynamic_sitemaps-2.0.0/lib/dynamic_sitemaps.rb:27:in `generate_sitemap'
/gems/dynamic_sitemaps-2.0.0/lib/dynamic_sitemaps/tasks/sitemap.rake:5:in `block (2 levels) in <top (required)>'

```

**Comment by stabenfeldt** [comment]
BTW, I'm using MongoID

**Comment by varmad** [comment]
Did any one solved this problem? I'm also getting the same.

**Comment by stabenfeldt** [comment]
I followed Advanced Rails Recipes' approach and wrote my own sitemap
generator. :-)

## 

Martin Stabenfeldt
Tlf: +47 93441707

**Comment by stulentsev** [comment]
https://github.com/lassebunk/dynamic_sitemaps/pull/28
