### ISSUE TITLE
undefined method `protocol'

### ISSUE THREAD

**Issue by Natd** [lassebunk/dynamic_sitemaps#31]
I need https, but this method doesnt work

Generating sitemap...
rake aborted!
NoMethodError: undefined method `protocol' for #<DynamicSitemaps::Generator:0x000000047b4f90>
/home/gabstez/vladproject/config/sitemap.rb:4:in`generate'
/home/gabstez/.rvm/gems/ruby-2.1.3/gems/dynamic_sitemaps-2.0.0/lib/dynamic_sitemaps/generator.rb:10:in `instance_eval'
/home/gabstez/.rvm/gems/ruby-2.1.3/gems/dynamic_sitemaps-2.0.0/lib/dynamic_sitemaps/generator.rb:10:in`generate'
/home/gabstez/.rvm/gems/ruby-2.1.3/gems/dynamic_sitemaps-2.0.0/lib/dynamic_sitemaps.rb:27:in `generate_sitemap'
/home/gabstez/.rvm/gems/ruby-2.1.3/gems/dynamic_sitemaps-2.0.0/lib/dynamic_sitemaps/tasks/sitemap.rake:5:in`block (2 levels) in <top (required)>'
/home/gabstez/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in `eval'
/home/gabstez/.rvm/gems/ruby-2.1.3/bin/ruby_executable_hooks:15:in`<main>'
Tasks: TOP => sitemap:build => sitemap:generate

**Comment by Natd** [comment]
ok it's worked if i specify

> gem 'dynamic_sitemaps', git: 'git@github.com:lassebunk/dynamic_sitemaps.git'

in Gemfile
i think in rubygems old version

**Comment by rastasheep** [comment]
+1 on this
Please update version on rubygems

Tnx!
